env:
   browser: true
   es2021: true
extends:
   - eslint:recommended
   - plugin:@typescript-eslint/recommended
parser: '@typescript-eslint/parser'
parserOptions:
   ecmaVersion: latest
   sourceType: module
plugins:
   - '@typescript-eslint'
rules: { '@typescript-eslint/no-unused-vars': [
            'error',
            { 'argsIgnorePattern': '^next$' }, # Ignore 'next' as the last argument
         ], '@typescript-eslint/no-explicit-any': 'warn', '@typescript-eslint/consistent-type-definitions': ['warn', 'interface'] }
